import type {Member,NavigationItem,PageBlock,RichNode,Role,SiteSettings,Taxonomy} from '@/lib/content/types';
export type DocumentKind='post'|'page';
export type DocumentStatus='draft'|'review'|'published'|'archived';
export type DocumentData={slug:string;title:string;excerpt:string;coverUrl:string|null;coverAlt:string;categoryId:string|null;tagIds:string[];body:RichNode;blocks:PageBlock[];description:string;featured:boolean;demo?:boolean};
export type AdminDocument={id:string;kind:DocumentKind;status:DocumentStatus;version:number;draft:DocumentData;published:DocumentData|null;authorId:string;authorName:string;publishedAt:string|null;updatedAt:string;deletedAt:string|null};
export type DocumentRevision={id:string;documentId:string;version:number;data:DocumentData;actorName:string;createdAt:string;note:string};
export type ActionResult<T=undefined>={ok:true;data:T}|{ok:false;error:string;code?:string};
export type AdminUser={id:string;name:string;email:string;role:Role;disabled:boolean;mustChangePassword:boolean};
export type MediaItem={id:string;url:string;filename:string;alt:string;mimeType:string;width:number;height:number;size:number;ownerId:string;createdAt:string};
export type DashboardData={total:number;drafts:number;review:number;published:number;recent:AdminDocument[]};
export type SaveDocumentInput={id?:string;kind:DocumentKind;expectedVersion?:number;data:DocumentData};
export type TransitionInput={id:string;expectedVersion:number;action:'submit'|'publish'|'return'|'unpublish'|'trash'|'restore'|'delete';note?:string};
export type SaveTaxonomyInput={id?:string;kind:'category'|'tag';name:string;slug:string;description?:string};
export type SettingsInput=SiteSettings;
export type MemberInput=Omit<Member,'id'> & {id?:string};
export type TaxonomyData={categories:Taxonomy[];tags:Taxonomy[]};
export type UserInput={id?:string;name:string;email:string;role:Role;disabled?:boolean;password?:string};
export type {Member,NavigationItem,PageBlock,RichNode,Role,SiteSettings,Taxonomy};
export const emptyDocument:DocumentData={slug:'',title:'',excerpt:'',coverUrl:null,coverAlt:'',categoryId:null,tagIds:[],body:{type:'doc',content:[{type:'paragraph'}]},blocks:[],description:'',featured:false};
