#!/usr/bin/env python3
"""Build Unicode-sliced WOFF2 files for Source Han Serif CN Medium.

Run from the repository root:
  uv run --with 'fonttools[woff]' python scripts/font-build.py
"""

from __future__ import annotations

from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Iterable

from fontTools import subset
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parent.parent
SOURCE_FONT = ROOT / "可参考字体" / "SourceHanSerifCN-Medium-6.otf"
OUTPUT_DIR = ROOT / "public" / "fonts"
CSS_FILE = OUTPUT_DIR / "fonts.css"
FILE_PREFIX = "darwin-editorial-serif-medium"
MAX_CODEPOINTS_PER_SLICE = 4096
GAP_BREAK = 256


def unicode_groups(codepoints: Iterable[int]) -> list[list[int]]:
    """Group cmap codepoints into compact, non-overlapping CSS ranges."""
    groups: list[list[int]] = []
    current: list[int] = []

    for codepoint in sorted(set(codepoints)):
        if current and (
            len(current) >= MAX_CODEPOINTS_PER_SLICE
            or codepoint - current[-1] > GAP_BREAK
        ):
            groups.append(current)
            current = []
        current.append(codepoint)

    if current:
        groups.append(current)

    return groups


def unicode_range(codepoints: list[int]) -> str:
    start, end = codepoints[0], codepoints[-1]
    if start == end:
        return f"U+{start:04X}"
    return f"U+{start:04X}-{end:04X}"


def build_slice(source: Path, codepoints: list[int], destination: Path) -> set[int]:
    options = subset.Options()
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    options.name_languages = ["*"]
    options.notdef_glyph = True
    options.notdef_outline = True

    font = TTFont(source, recalcBBoxes=False, recalcTimestamp=False)
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)
    # Subsets are a Modified Version under OFL; do not retain Adobe's reserved
    # primary family name. Preserve copyright/license records and all glyphs.
    names = {1: "Darwin Editorial Serif", 2: "Medium", 3: "DarwinEditorialSerif-Medium-v1",
             4: "Darwin Editorial Serif Medium", 6: "DarwinEditorialSerif-Medium",
             16: "Darwin Editorial Serif", 17: "Medium"}
    for record in list(font["name"].names):
        if record.nameID in names:
            font["name"].setName(names[record.nameID], record.nameID,
                                 record.platformID, record.platEncID, record.langID)
    if "CFF " in font:
        cff = font["CFF "].cff
        cff.fontNames = ["DarwinEditorialSerif-Medium"]
        cff.topDictIndex[0].FullName = "Darwin Editorial Serif Medium"
        cff.topDictIndex[0].FamilyName = "Darwin Editorial Serif"
    font.flavor = "woff2"
    font.save(destination)
    font.close()

    result = TTFont(destination, recalcBBoxes=False, recalcTimestamp=False)
    try:
        return set(result.getBestCmap())
    finally:
        result.close()


def css_for(slices: list[tuple[str, list[int]]]) -> str:
    rules = [
        "/* Generated by scripts/font-build.py. Do not edit manually. */",
        "",
    ]
    for filename, codepoints in slices:
        rules.extend(
            [
                "@font-face {",
                '  font-family: "Darwin Editorial Serif";',
                "  font-style: normal;",
                "  font-weight: 500;",
                "  font-display: swap;",
                f'  src: url("/fonts/{filename}") format("woff2");',
                f"  unicode-range: {unicode_range(codepoints)};",
                "}",
                "",
            ]
        )
    return "\n".join(rules)


def main() -> None:
    if not SOURCE_FONT.is_file():
        raise FileNotFoundError(f"Source font not found: {SOURCE_FONT}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    source = TTFont(SOURCE_FONT, recalcBBoxes=False, recalcTimestamp=False)
    try:
        source_codepoints = set(source.getBestCmap())
    finally:
        source.close()

    if not source_codepoints:
        raise RuntimeError("The source font does not expose a Unicode cmap.")

    groups = unicode_groups(source_codepoints)
    created_slices: list[tuple[str, list[int]]] = []
    output_codepoints: set[int] = set()

    with TemporaryDirectory(dir=OUTPUT_DIR) as temporary_directory:
        temporary_dir = Path(temporary_directory)
        for index, group in enumerate(groups, start=1):
            filename = f"{FILE_PREFIX}-{index:02d}.woff2"
            temporary_file = temporary_dir / filename
            output_codepoints.update(build_slice(SOURCE_FONT, group, temporary_file))
            created_slices.append((filename, group))

        missing = source_codepoints - output_codepoints
        if missing:
            raise RuntimeError(
                f"Unicode coverage verification failed; {len(missing)} codepoints are missing."
            )

        for stale_file in [*OUTPUT_DIR.glob(f"{FILE_PREFIX}-*.woff2"), *OUTPUT_DIR.glob("source-han-serif-cn-medium-*.woff2")]:
            stale_file.unlink()
        for filename, _ in created_slices:
            (temporary_dir / filename).replace(OUTPUT_DIR / filename)

    CSS_FILE.write_text(css_for(created_slices), encoding="utf-8")
    print(
        f"Built {len(created_slices)} WOFF2 slices with {len(source_codepoints)} Unicode codepoints "
        f"in {OUTPUT_DIR.relative_to(ROOT)}."
    )


if __name__ == "__main__":
    main()
